// import localFont from "next/font/local";
import "./globals.css";

export const metadata = {
  title: "Neighbor View | Learn more about your neighborhood",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <meta charSet="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      </head>
      <body>{children}</body>
    </html>
  );
}
